### ISSUE TITLE
Question: Why do we store the user in local storage vs. just calling window.netlifyIdentity.currentUser() when we need that info?

### ISSUE THREAD

**Issue by renschler** [sw-yx/jamstack-hackathon-starter#6]
As always there are many ways to do things, I'm not saying the way it's done here is wrong, just trying to learn.

Is there a reason you needed to store things in local storage, or could you have gotten away with a call to window.netlifyIdentity.currentUser() instead of using getUser() when you needed user info?

I see that the isLoggedIn function doesn't call getUser(), it's relying on a call to netlifyIdentity.

For anyone else trying to implement auth for a gatsby site I found these resources useful (in addition to this repo):
- https://www.gatsbyjs.org/blog/2019-03-21-add-auth0-to-gatsby-livestream/
- https://www.gatsbyjs.org/docs/authentication-tutorial/

**Comment by swyxio** [comment]
i'm not really sure, its been a while since i made this. i think you want it in local storage just so you can reopen it in future and still grab it off local storage so you dont need to log in again. the implementation could probably be better. feel free to PR improvements!

i'm vaguely aware of a bug in other projects where this mechanism doesnt work, and you have to log in again when you refresh (i.e. the identity is only kept in memory). would love to have a good setup so that just never happens
