### ISSUE TITLE
Question: 404 when searching url directly

### ISSUE THREAD

**Issue by CarlBrownDatacom** [sw-yx/jamstack-hackathon-starter#7]
Hi,

When i search directly to 'https://jamstack-hackathon-starter.netlify.com/app/login' the server returns the 404 error page as its not found, it then finds the client side version and renders again with the new output.

Is there anyway to get around showing the 404 error page first? 
should i even care about this?

this is the first time ive added am issue/question on a repo, if this is the wrong place to do this please let me know.

Thanks

**Comment by swyxio** [comment]
no problem. what you’re running into is the SPA redirects problem. https://www.netlify.com/docs/redirects/#history-pushstate-and-single-page-apps

make sense? because app/login is dynamic theres no html file to serve. so you have to send users to the right location from the serverside (app.html), then use clientside routing (in our case @reach/router embedded in gatsby) to render app/login

**Comment by CarlBrownDatacom** [comment]
I think i understand. i will try a POC
something like `/app/*    /app.html   200`

**Comment by swyxio** [comment]
yeah. i probably need to add that in this starter too. welcome a PR once you've figured it out, i'm not working on this right now
